### ISSUE TITLE
State gets lost with "soft" reset when using @vite-pwa/nuxt and nuxt-auth-utils

### ISSUE THREAD

**Issue by vincentdorian** [vite-pwa/nuxt#111]
Hi there 👋

I have an issue with using a Nuxt App with PWA functionality when using nuxt-auth-utils for user authentication. To see whether a user is still authenticated, a middleware using the nuxt-auth-utils is used. 

Here, the Nuxt useState composable is used to save the session data into the payload. 

When using a "hard" refresh, the state for the session gets fetched correctly and the user remains logged in, however the state gets lost when using a normal refresh. 

The following repo contains the repro with two branches: the main branch with PWA functionalities and the "no-pwa" branch, which does not have PWA but auth works as expected. 

https://github.com/vincentdorian/nuxt-pwa-with-auth.git

I have already tried various workarounds to fetch the session via hooks, but have not been able to restore the state before the middleware gets activated.

**Comment by userquin** [comment]
Cannot test the app, added `.env` with the password but getting nitro error on login page and login action, do I need to configure some missing entry in the nuxt.config.ts file?:

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/a2e288dd-1ef0-469a-aea0-a5f4f3f06aa5)

**Comment by userquin** [comment]
PR sent to the repo.

**Comment by vincentdorian** [comment]
Hiya, Thanks for getting back me. 
Other than the NUXT_SESSION_PASSWORD, which should be 32 chars min (which yours is), there should be no additional configuration needed for the repro. That's quite odd. I am using pnpm on WSL, which you seem to do too. 

I will try using the configuration in the PR.

**Comment by userquin** [comment]
I'm not using WSL, I'm using Windows 10 PRO command prompt.

**Comment by userquin** [comment]
The PR sent solves the error: https://github.com/vincentdorian/nuxt-pwa-with-auth/pull/1#issuecomment-1879817143
