### ISSUE TITLE
pwa does not cache data in Nuxt 3 SSR

### ISSUE THREAD

**Issue by antonyd89** [vite-pwa/nuxt#120]
**Description:**
The @vite-pwa/nuxt plugin does not cache anything in the preview mode (`nuxi build` + `nuxi start` commands), as the cache storage appears to be empty. However, in dev mode, the cache storage contains data.

App works on Nuxt 3 with the `ssr:true` setting, and most of the pages in my app are dynamic and fetched from [Storyblok CMS](https://www.storyblok.com/a/storyblok-home?utm_source=google&utm_medium=cpc&utm_campaign=PA_SEA_Brand&utm_term=storyblok&utm_device={utm_device}&gad_source=1&gclid=CjwKCAjw48-vBhBbEiwAzqrZVM2RKNBlOdXuT6V5QZ5eTYM7Sfpz0f41BxqdUvC-c422wYRLWVZ1vRoC-lAQAvD_BwE). I specifically need to cache the home page. Therefore, I have configured the home page to be prerendered on the server via [routeRules](https://nuxt.com/docs/api/nuxt-config#routerules-1) for the home page `"/"` set `prerender:true` option, additionally to nuxt.config added `nitro.prerender.routes: ['/']` 

**Steps to Reproduce:**

1. Install Nuxt 3 using the command `npx nuxi@latest init`. Make sure that the project is configured to use Yarn packages.
2. Navigate to the `pages` directory within the project.
3. Instead of the `index.vue` page, create a dynamic page, for example, `[...slug].vue`.
4. Write a fetch request to the Storyblok API or any other API within the created dynamic page.
5. Next, execute `yarn run build` followed by `yarn run start`.
6. Open the site in a browser and check the **Cache Storage** using browser devtools/application tab.

**Expected Behavior:**
I expected the @vite-pwa/nuxt plugin to cache the home page content in preview mode / production.

**Actual Behavior:**
The cache storage remains empty in preview mode, despite the page content being available in dev mode.

**Plugin Version:**  `"@vite-pwa/nuxt": "^0.6.0"`

**My Environment:**

- Operating System: macOS Monterey 12.5.1 (21G83) 
- Browser: Google Chrome Version 122.0.6261.128 (Official Build) (arm64)
- yarn: 1.22.19
-  @storyblok/nuxt: ^5.7.9 
- nuxt: ^3.8.2

Nuxt.config:
```

> `defineNuxtConfig({
>   modules: [
>     [
>       '@storyblok/nuxt',
>       {
>         accessToken: 'token value.....',
>       },
>     ],
>       '@vite-pwa/nuxt',
>   ],
>   pwa: {
>     registerType: 'autoUpdate',
>     manifest: {
>       showInstallPrompt: true,
>       name: 'company-name',
>       short_name: 'company-name',
>       description: 'description site',
>       crossorigin: 'use-credentials',
>       dir: 'auto',
>       lang: 'es-ES',
>       display: 'standalone',
>       orientation: 'any',
>       scope: '/',
>       background_color: '#ffffff',
>       theme_color: '#ffffff',
>       icons: [
>         {
>           src: '/android-chrome-192x192.png',
>           sizes: '192x192',
>           type: 'image/png',
>         },
>         {
>           src: '/android-chrome-512x512.png',
>           sizes: '512x512',
>           type: 'image/png',
>         },
>         {
>           src: '/maskable_icon.png',
>           sizes: '196x196',
>           type: 'image/png',
>           purpose: 'maskable',
>         },
>       ],
>     },
>     meta: {
>       name: 'meta name title',
>       author: 'company-name',
>       description: 'description goes here...',
>       charset: 'utf-8',
>       theme_color: '#ffffff',
>       lang: 'es-ES',
>     },
>     strategies: 'generateSW',
>     workbox: {
>       navigateFallback: '/',
>       navigateFallbackAllowlist: [/^\/*/],
>       globPatterns: ["**/*.{js,html,css,png,ico,woff2,svg,json}"],
>       runtimeCaching: [
>         {
>           urlPattern: ({ sameOrigin, request }) => sameOrigin && request.mode === 'navigate',
>           handler: 'NetworkFirst',
>           options: {
>             plugins: [{
>               handlerDidError: async ({ state }) => {
>                 return state?.fallback ? Response.redirect('/', 302) : undefined
>               },
>               cacheWillUpdate: async ({ response }) => response?.status === 200 ? response : null,
>               handlerWillRespond: async (ctx) => {
>                 if (!ctx.response) {
>                   ctx.state ??= {}
>                   ctx.state.fallback = true
>                 }
> 
>                 return ctx.response
>               },
>             }],
>           },
>         },
>       ],
>     },
>     devOptions: {
>       enabled: true,
>       suppressWarnings: false,
>       type: 'module',
>     },
>   },
> })`
> 

```

Here is [repo](https://github.com/antonyd89/pwa-test-reprodution) to reproduce the issue

**Comment by antonyd89** [comment]
As it turend out the root cause of this issue lies within a bug present in the devtools of the Chrome browser. When executing the 'nuxi start' command in the terminal, the URL displayed indicates that the server is listening on http://[::]:3000. However, upon opening this URL in the browser, the devtools fail to display any information in the Application tab or Cache Storage.

Interestingly, accessing the application via http://localhost:3000/ resolves the problem, as the devtools correctly display cached data in the Application tab/Cache Storage.

**Comment by antonyd89** [comment]
As it turend out the root cause of this issue lies within a bug present in the devtools of the Chrome browser. When executing the 'nuxi start' command in the terminal, the URL displayed indicates that the server is listening on http://[::]:3000. However, upon opening this URL in the browser, the devtools fail to display any information in the Application tab or Cache Storage.

Interestingly, accessing the application via http://localhost:3000/ resolves the problem, as the devtools correctly display cached data in the Application tab/Cache Storage.

**Comment by userquin** [comment]
`navigateFallbackAllowlist: [/^\/*/],` is wrong since this configuration will force the sw to intercept any url that's not `/`, we want to allow only `/` and so we need `navigateFallbackAllowlist: [/^\/$/],`

**Comment by antonyd89** [comment]
> `navigateFallbackAllowlist: [/^\/*/],` is wrong since this configuration will force the sw to intercept any url that's not `/`, we want to allow only `/` and so we need `navigateFallbackAllowlist: [/^\/$/],`

Yes, that is also correct. Thank you for your assistance in debugging and resolving this issue
