### ISSUE TITLE
Firefox injectManifest not working

### ISSUE THREAD

**Issue by Flashantik** [vite-pwa/nuxt#122]
Starting Playground with run dev-sw (with injectManifest)  The service worker is not installed, there is also an error in `$pwa.registrationError`. No error in console, just $pwa.registrationError
<img width="1404" alt="Screenshot 2024-03-18 at 15 53 50" src="https://github.com/vite-pwa/nuxt/assets/25429994/4ea0f91c-084c-4fa0-a71f-4d9a64fba156">

run dev works fine. 
<img width="1337" alt="Screenshot 2024-03-18 at 15 52 48" src="https://github.com/vite-pwa/nuxt/assets/25429994/4a9b1aeb-cba6-40f0-93c9-b4595cf99107">

in chrome and safari run dev-sw works fine too

**Comment by userquin** [comment]
You cannot register any service worker with type module in non chromium based browsers, to test the sw you need chrome/chromium/edge.
