### ISSUE TITLE
non-precached-url: non-precached-url :: [{"url":"index.html"}]

### ISSUE THREAD

**Issue by RifatMahmudno-1** [vite-pwa/nuxt#13]
I'm having this issue. 
I'm using nuxt 3. The website is a multipage website.
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at E.createHandlerBoundToURL (http://localhost:3000/workbox-3625d7b0.js:1:13533)
    at Object.createHandlerBoundToURL (http://localhost:3000/workbox-3625d7b0.js:1:15228)
    at http://localhost:3000/sw.js:1:4222
    at http://localhost:3000/sw.js:1:565

**Comment by RifatMahmudno-1** [comment]
registerType: 'autoUpdate',
registerWebManifestInRouteRules: true,
workbox: {
	globPatterns: ['**/*.{js,css,html,png,svg,jpg,ttf}']
},

**Comment by userquin** [comment]
@RifatMahmudno-1 add `navigationFallback: '/'` to `workkbox` option, you can check it in playground configuration https://github.com/vite-pwa/nuxt/blob/main/playground/nuxt.config.ts#L38

**Comment by RifatMahmudno-1** [comment]
Doesn't work. I tried adding navigateFallback: '/'. The error is still there.
Then I tried this and it worked:
		workbox: {
			globPatterns: ['**/*.{js,css,html,png,svg,jpg,ttf}'],
			navigateFallback: null,
			additionalManifestEntries: [{ url: '/', revision: new Date().getTime().toString() }]
		},

**Comment by userquin** [comment]
@RifatMahmudno-1 on build or dev? if you're using dev with `devOptions.enabled = true` add the same entry `devOptions.navigateFallback = '/'`

can you provide a repo link (GitHub or stackblitz)?

**Comment by RifatMahmudno-1** [comment]
You can clone this repository, run and reproduce that error.
Run in production mode. `npm run build && npm run preview`
[Repo link](https://github.com/RifatMahmudno-1/vite-pwa_error)

**Comment by userquin** [comment]
To allow your app work offline you need precaching in the service worker and so at least one static page acting as app shell: you will need to add `nitro.prerender.routes: ['/']` to your nuxt configuration.

**Comment by RifatMahmudno-1** [comment]
Working Thanks
