### ISSUE TITLE
Uncaught ReferenceError: __NUXT_ASYNC_CONTEXT__ is not defined

### ISSUE THREAD

**Issue by Harm-Nullix** [vite-pwa/nuxt#131]
Using Nuxt 3.10 and above,`__NUXT_ASYNC_CONTEXT__` is not defined inside the service worker.
Already tried bumping @vite-pwa/nuxt to 0.6.0 but it does not resolve the issue.

```
    "@vite-pwa/nuxt": "0.6.0",
    "nuxt": "3.11.2",
└─ @nuxt/vite-builder@3.11.2
└─ @nuxt/schema@3.11.2

```
nuxt config:
```
  vite: {
    define: {
      'process.env.DEBUG': false,
      __NUXT_ASYNC_CONTEXT__: false
    },
},
  experimental: {
    asyncContext: false,
  },
```

Error:
<img width="1003" alt="image" src="https://github.com/vite-pwa/nuxt/assets/80104552/e8512946-4d2e-4cc9-b142-6e958f9184f9">

From ./node_modules/nuxt/dist/app/nuxt.js:9
```
getContext("nuxt-app", {
    asyncContext: !!__NUXT_ASYNC_CONTEXT__ && false
});
```

It is defined in the browser, but when the service worker tries to load it failes because of this error.

**Comment by Harm-Nullix** [comment]
## addition
When I do set the value `__NUXT_ASYNC_CONTEXT__` hard to false or true, I get another error from the service worker:

Uncaught ReferenceError: window is not defined

This comes from the interval.js. It looks for `import.meta.client ? window.setInterval : ()... `and then crashes because there is no window in a service worker

**Comment by userquin** [comment]
https://github.com/nuxt/nuxt/issues/25620

**Comment by userquin** [comment]
so, nuxt will try to use internal `setInterval` and will check only for client (import.meta.client)

why are you using setInterval inside the service worker? can you try `self.setTimeout`?

**Comment by Harm-Nullix** [comment]
Of course, that is only the second issue, I could work around that. Making a timeout out of an interval is not that hard.
FWI: The SW does a "ping" that calls a server.
