### ISSUE TITLE
@vite-pwa/nuxt and vue-tsc conflict

### ISSUE THREAD

**Issue by Chocopieca** [vite-pwa/nuxt#134]
I caught 10 errors indicating invalid imports after I put @vite-pwa/nuxt together with vue-tsc.
Is there any way to fix this ?

https://nuxt.com/docs/guide/concepts/typescript
I followed these instructions

![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/48634382/23b84a65-e82e-4e9a-b682-1a7cc30da023)
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/48634382/74d100c8-2a7f-4f1e-9868-9a33fa3d4919)
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/48634382/ac375910-f585-4a11-b1d1-a2d73cc8de8b)
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/48634382/f554127a-1e64-4592-bd66-77a9c9717255)
![image](https://github.com/vite-pwa/vite-plugin-pwa/assets/48634382/2a9adce7-91f9-4c6d-882e-94cfd4eadd9c)

node.js v21.7.3
npm 10.5.0

package.json

`"dependencies": {
    "@nuxtjs/i18n": "^8.3.1",
    "@nuxtjs/robots": "^3.0.0",
    "@pinia/nuxt": "^0.5.1",
    "nuxt-clarity-analytics": "^0.0.6",
    "nuxt-security": "^2.0.0-beta.5",
    "pinia": "^2.1.7",
    "vue-router": "^4.3.2"
  },
  "devDependencies": {
    "@nuxt/devtools": "^1.3.1",
    "@nuxt/eslint-config": "^0.3.12",
    "@nuxt/types": "^2.17.3",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "@nuxtjs/eslint-module": "^4.1.0",
    "@nuxtjs/tailwindcss": "^6.12.0",
    "@vite-pwa/nuxt": "^0.7.0",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-anti-trojan-source": "^1.1.1",
    "eslint-plugin-css-modules": "^2.12.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "eslint-plugin-prettier": "^5.1.3",
    "eslint-plugin-security-node": "^1.1.4",
    "nuxt": "^3.11.2",
    "prettier-plugin-tailwindcss": "^0.5.14",
    "sass": "^1.77.1",
    "stylelint": "^16.5.0",
    "stylelint-config-prettier-scss": "^1.0.0",
    "stylelint-config-standard-scss": "^13.1.0",
    "typescript": "^5.4.5",
    "vue-tsc": "^1.8.27"
  }`

typescript.json
`{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable",
      "WebWorker",
      "DOM"
    ],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "~/*": [
        "./*"
      ],
      "@/*": [
        "./*"
      ]
    },
    "types": [
      "@nuxt/types",
      "@types/node",
      "@vite-pwa/nuxt/dist/types",
    ]
  },
  "exclude": [
    "node_modules"
  ],
  "extends": "./.nuxt/tsconfig.json"
}
`

**Comment by userquin** [comment]
![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/60dc348c-4b37-4115-9cbd-d1033bcdfccd)

**Comment by Armane-Pro** [comment]
this happens only when you override baseURL 
add this to your tsconfig path ✅

```
"#pwa": ["node_modules/@vite-pwa/nuxt/dist/runtime/composables/index"]
```
