### ISSUE TITLE
Vite-pwa/nuxt not caching pages on a client-side rendered app

### ISSUE THREAD

**Issue by felixfavour** [vite-pwa/nuxt#141]
Hi, vite-pwa team, thank you for the beautiful work with this tool.

I had no issues with it until I had to cache pages on a CSR app with Nuxt. 

I have looked at other codebases that use this package with full offline support, and I tried to model precisely how they integrated. Still, I have not been successful (I also noticed that those codebases had SSR on).

Could it be that the offline support only works for SSR? Asking because the biggest value of the project I am building is full offline support.

I would love any help I can get on this 🙏🏿 

```
nuxt version: 3.10.3
vite-pwa/nuxt version: 0.8.0
```

**Comment by userquin** [comment]
What's the problem? Can you describe the problem? Provide a minimal reproduction using https://vite-pwa-org.netlify.app/guide/scaffolding.html , select vue the nuxt when selecting the framework.

**Comment by userquin** [comment]
You can try adding `[/^\/$/]` to workbox.navigateFallbackAllowlist` since html pages will not be generated.
