### ISSUE TITLE
assets generation not working with nuxt 4 without this workaround

### ISSUE THREAD

**Issue by GreyXor** [vite-pwa/nuxt#143]
hello,
I'm generating assets with 
```ts
    pwaAssets: {
      preset: "minimal-2023",
    },
```

And it's not working because now in nuxt 4, `the new Nuxt default srcDir is app/ by default, and most things are resolved from there.`".

That's mean I had to add this config:
```ts
  pwa: {
    pwaAssets: {
      image: "../public/favicon.svg"
    },
```
i'm just opening this issue to track nuxt v4 dev and letting you know the workaround

**Comment by userquin** [comment]
check https://github.com/vite-pwa/nuxt/issues/137 , I'll try to fix the problem this weekend...

**Comment by GreyXor** [comment]
Thanks
