### ISSUE TITLE
Build Failures with TypeScript's noUnusedLocals Compiler Option

### ISSUE THREAD

**Issue by vinoddotcom** [vite-pwa/nuxt#160]
In Nuxt.js project that uses TypeScript, enabling the noUnusedLocals option in tsconfig.json causes the build to fail.

**Screenshot:** 
![Screenshot from 2024-09-04 18-28-03](https://github.com/user-attachments/assets/8845a794-e719-4869-a758-29e83b4a6216)

**Minimum Reproduction:**  https://stackblitz.com/edit/github-zjpmae?file=package.json

Steps: 

1. `npm i`
2. `npm run test`
3. See error

**Comment by userquin** [comment]
Did you have `@vite-pwa/assets-generator` installed?

**Comment by userquin** [comment]
upps, forgot it, I'm going to release a new patch version in a few minutes, I need to remove unused import

**Comment by vinoddotcom** [comment]
Please take a look at the screenshot related to the project I’m currently working on. There were multiple import errors initially flagged as 'not found.' However, after disabling the `noUnusedLocals` rule in the TypeScript configuration, these errors were resolved.

**Comment by userquin** [comment]
No idea why checking types from `node_modules`, here your reproduction (moved `noUnusedLocals` to nuxt config file and added `vite-plugin-pwa`) working: https://stackblitz.com/edit/github-zjpmae-mvu5fh?file=nuxt.config.ts

**Comment by vinoddotcom** [comment]
Here is a minimum reproduction of my case where multiple import errors were initially flagged as 'not found. 

Minimum Reproduction: https://stackblitz.com/edit/github-yp7irr?file=package.json

I used to register the service worker through the plugins folder.
**Check:** plugins -> init.client.ts

Steps: 
1. `npm run clean-install`
2. `clean-test`
3. See error

**Comment by vinoddotcom** [comment]
@userquin Node_module is excluded in tsconfig.json, but somehow it still checks all `.vue` files including node_modules.

**Comment by vinoddotcom** [comment]
@userquin After running

```
npm run clean-install
npm run clean-test
```

I found these lines in `./nuxt/tsconfig.json`, which is why TypeScript checks those files inside the node module.

```
    "../node_modules/@vite-pwa/nuxt/runtime",
    "../node_modules/@vite-pwa/nuxt/dist/runtime",
``` 
Sure! Here is the rewritten text:

Please remember the following text:

In `node_modules/@vite-pwa/nuxt/dist/runtime`, file types are imported with `#build/`. This is configured in `./nuxt/tsconfig.json`. as
```
      "#build/": [
        "./"
      ],
``` 
In general, the default character we use is either `~` or `@`, which is configured as such.
```
      "~/*": [
        "../*"
      ],
      "@/*": [
        "../*"
      ],
``` 
Could you please check if it should be `#build/` or `@`?

**Comment by userquin** [comment]
It should be `#build/` since the types are generated inside the .nuxt folder, check pwa-icons subfolder.

**Comment by vinoddotcom** [comment]
Can you please investigate why this issue is occurring based on its reproduction (https://stackblitz.com/edit/github-yp7irr?file=package.json)?

**Comment by vinoddotcom** [comment]
> @userquin Here is a minimum reproduction of my case where multiple import errors were initially flagged as 'not found.
> 
> Minimum Reproduction: https://stackblitz.com/edit/github-yp7irr?file=package.json
> 
> I used to register the service worker through the plugins folder. **Check:** plugins -> init.client.ts
> 
> Steps:
> 
> 1. `npm run clean-install`
> 2. `npm run clean-test`
> 3. See error

@userquin Can you please investigate why this issue is occurring based on its reproduction (https://stackblitz.com/edit/github-yp7irr?file=package.json)?

**Comment by userquin** [comment]
It is fine on my local, using node 20.10.0.

**Comment by userquin** [comment]
can you update vue to `3.5.3`? I'm getting some error using Nuxt `3.13.1` and internal `useId`:
```json
  "devDependencies": {
    "@vite-pwa/nuxt": "0.10.5",
    "nuxt": "3.13.1",
    "typescript": "5.5.4",
    "vue": "^3.5.3",
    "vue-tsc": "2.1.6"
  },
  "resolutions": {
    "vue": "3.5.3"
  }
```

**Comment by vinoddotcom** [comment]
@userquin, thank you for your response. Everything is running fine now.
