### ISSUE TITLE
Nuxt Compatibilty 4 Glob error

### ISSUE THREAD

**Issue by moshetanzer** [vite-pwa/nuxt#176]
Hi,

Hope you well.

Been getting this on all Nuxt 4 builds. Any clues?  

````
vite-pwa/vite-plugin-pwa#15 149.6 PWA v0.21.0
vite-pwa/vite-plugin-pwa#15 149.6 mode      generateSW
vite-pwa/vite-plugin-pwa#15 149.6 precache  3 entries (0.21 KiB)
vite-pwa/vite-plugin-pwa#15 149.6 files generated
vite-pwa/vite-plugin-pwa#15 149.6   ../.output/public/sw.js
vite-pwa/vite-plugin-pwa#15 149.6   ../.output/public/workbox-4723e66c.js
vite-pwa/vite-plugin-pwa#15 149.6 warnings
vite-pwa/vite-plugin-pwa#15 149.6   One of the glob patterns doesn't match any files. Please remove or fix the following: {
vite-pwa/vite-plugin-pwa#15 149.6   "globDirectory": "/app/.output/public",
vite-pwa/vite-plugin-pwa#15 149.6   "globPattern": "**/_payload.json",
vite-pwa/vite-plugin-pwa#15 149.6   "globIgnores": [
vite-pwa/vite-plugin-pwa#15 149.6     "**/node_modules/**/*",
vite-pwa/vite-plugin-pwa#15 149.6     "sw.js",
vite-pwa/vite-plugin-pwa#15 149.6     "workbox-*.js"
vite-pwa/vite-plugin-pwa#15 149.6   ]
vite-pwa/vite-plugin-pwa#15 149.6 }

````

**Comment by moshetanzer** [comment]
Just manifest with icons and short name and name and description.

**Comment by userquin** [comment]
Maybe we need to check v4 compat mode and use róotDor instead srcDir, will check it tmr.

Can you check it using create pwa https://vite-pwa-org.netlify.app/guide/scaffolding.html ? Select vue then Nuxt 4 and follow the wizard

**Comment by moshetanzer** [comment]
Hey @userquin yip! that is the issue! Build fine when using the nuxt 4 compat template!

**Comment by moshetanzer** [comment]
@userquin any temp workaround. What can I set the srcdir as?

**Comment by userquin** [comment]
Check https://github.com/vite-pwa/nuxt/blob/main/src/utils/config.ts

**Comment by userquin** [comment]
You need to change both, `workbox.globDirectory ` and `outDir`: previous module will not configure `workbox.globDirectory`.

**Comment by userquin** [comment]
If you're using SSR (ssr: true or not configured or running `nuxt generate` ), check also if the `sw.js` and `workbox-**.js` present in `.output/server` folder.

**Comment by moshetanzer** [comment]
> If you're using SSR (ssr: true or not configured or running `nuxt generate` ), check also if the `sw.js` and `workbox-**.js` present in `.output/server` folder.

am using ssr, not present in `.output/server` only in `public`

**Comment by userquin** [comment]
Add this in your nuxt config file: 
```js
import { createResolver } from '@nuxtjs/kit'` 

const { resolve } = createResolver(import.meta.url)

const outDir = resolve('./.output/public')
```

**Comment by moshetanzer** [comment]
that wont work nuxtjs kit is not available in nuxt config if not module

**Comment by userquin** [comment]
or
```js
import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'

const outDir = fileURLToPath(new URL('./.output/public', import.meta.url))
```

**Comment by userquin** [comment]
Use `__dirname` instead of `import.meta.url`, you can also add `"type": "module",` to your package.json

**Comment by moshetanzer** [comment]
Nope, sorry - none of this works. of course type is set to module - but nuxt kit is only availble as far as i understand in an actula nuxt module context? 

@danielroe any simple workaround for the moment? I see you did the nuxt 4 compat version for the scaffold cli

**Comment by userquin** [comment]
If repo created using `create-pwa` works, why your repository is not working? Did you follow the instructions in nuxt docs https://nuxt.com/docs/getting-started/upgrade#new-directory-structure (check Migration Steps a few line below)?

**Comment by moshetanzer** [comment]
Hey. Of course have quite a few projects running on v4 compact for about 3 months already!

I think that the specific nuxt module is not compatible with v4 yet. Even though when scaffolding it is since it isn't using the same module?

**Comment by userquin** [comment]
🙏 provide a minimal reproduction with your issue, I will check what's happening...

**Comment by moshetanzer** [comment]
seems like this was a cache issue was using experimntal build cache on swapover from Nuxt 3 to 4 - which for some reason even after setting to false was persisting in production - this is not a bug as far as i can tell.
