### ISSUE TITLE
Glob Pattern Error

### ISSUE THREAD

**Issue by melishev** [vite-pwa/nuxt#24]
Nuxt: 3.2.2
vite-plugin-pwa: 0.14.4
@vite-pwa/nuxt: 0.0.6

When I run the application with the nuxt dev command, I get a similar error:
```js
 WARN  warnings
  Some items were passed to additionalManifestEntries without revisioning info. This is generally NOT safe. Learn more at https://bit.ly/wb-precache.
  - /

  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/matvejmelishev/Desktop/example/client/.nuxt/dev-sw-dist",
  "globPattern": "**/*.{js,css,html}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}
```

But my configuration of the plugin with respect to global patterns is absolutely default

**Comment by jakhsu** [comment]
Hi @melishev  I just ran into the exact problem when trying to do PWA on a very minimal nuxt 3 project. How did you solve the issue?

**Comment by nicgene** [comment]
Same here. Any solution? @melishev

**Comment by userquin** [comment]
@jakhsu this is just a warning, not an error: it is only on dev server with `devOptions.enable=true`, we're only intercepting configured `navigateFallback` via `allow` option.

**Comment by jakhsu** [comment]
@userquin Thanks for the reply and explanation!
