### ISSUE TITLE
$pwa is of type 'unknown' type error

### ISSUE THREAD

**Issue by vasilistotskas** [vite-pwa/nuxt#28]
More in the screenshot above , any ideas how to resolve this ?

![pwa](https://user-images.githubusercontent.com/60323306/225292138-fb7e9e12-86d8-4a75-8d36-b0ccb2ce2a7c.png)

**Comment by userquin** [comment]
@vasilistotskas have you run `pnpm nuxi prepare`?

**Comment by vasilistotskas** [comment]
yes i did , this happens after i updated nuxt to 3.3.1 , but in version 3.2 didnt get the error but the $pwa was still uknown type , the "not good" solution i did for now is :

```
const pwa = useNuxtApp().$pwa as {
	offlineReady: boolean
	needRefresh: boolean
	showInstallPrompt: boolean
	updateServiceWorker: () => void
	install: () => void
	cancelInstall: () => void
	cancelPrompt: () => void
}
```

**Comment by userquin** [comment]
@vasilistotskas I'll check latest changes on Nuxt

**Comment by userquin** [comment]
@vasilistotskas https://youtrack.jetbrains.com/issue/IDEA-315801/TypeScript-module-resolution-not-working-properly
