### ISSUE TITLE
No page is added to precache after visit

### ISSUE THREAD

**Issue by lovkyndig** [vite-pwa/nuxt#31]
I'm not able to write the workbox sw-script by my self, therefor I am using generateSW.  

_I want the pages to be cached after use, so I can use them offline in my pwa._
But no page is added to workbox-precache after visit.
The service-worker is REDUNDANT.

### My nuxt.config
``` 
 pwa: {
    strategies: 'generateSW',
    injectRegister: 'auto',
    registerType: 'autoUpdate',
    workbox: {
      navigateFallback: '/',
      globPatterns: ['**/*.{js,css,html,svg,ico,png}'],
      globIgnores: ['google*.html''],
      cleanupOutdatedCaches: true,
    },
    devOptions: {
      enabled: true,
      navigateFallback: '/'
    },
  },
```

[Here is my deployment on github](https://github.com/lovkyndig/kirkepostille) and [Vercel](https://kirkepostille.vercel.app)

**Comment by userquin** [comment]
@lovkyndig review `globPatterns`, you are including everything, you only need the client and prerendered kit output folders:
https://github.com/vite-pwa/sveltekit/blob/main/examples/sveltekit-ts/vite.config.ts#L70

**Comment by userquin** [comment]
@lovkyndig try to update your `workbox.globPatterns` entry, since you are including everything in the sw precache manifest, workbox is duplicated (once for dev-dist folder and once for production sw)

https://github.com/vite-pwa/nuxt/blob/main/playground/nuxt.config.ts#L51

About this, it is not being used on build, `devOptions` will be only used when running dev server: 
```ts
    devOptions: {
      enabled: true // CHANGE TO FALSE ON PRODUCTION
    },
```

**Comment by lovkyndig** [comment]
Whow this was very fast and incredibly good suggestions for solutions. I'll try it out. You are really very quick to help.

**Comment by lovkyndig** [comment]
I changed something and the old errors is fixed, but two new errors was born.
The problem with runtimecache is still there, nothing changed about that.

**Comment by userquin** [comment]
@lovkyndig have you added VitePWAManifest to you app vue or layouts? https://vite-pwa-org.netlify.app/frameworks/nuxt.html

It is removed in your repo, in app.vue...

**Comment by lovkyndig** [comment]
Thank you very much for good advice! I will try to add the VitePWAManifest in app.vue

**Comment by lovkyndig** [comment]
The problem is solved in [issue 32)(https://github.com/vite-pwa/nuxt/issues/32).

If you aren't using pwa.manifest, the manifest-file have to be saved in two types, json AND webmanifest.
StackOverflow write about the file types [here](https://stackoverflow.com/questions/52129281/manifest-json-vs-manifest-webmanifest).
