### ISSUE TITLE
bad-precaching-response - url - manifest.webmanifest - 404

### ISSUE THREAD

**Issue by lovkyndig** [vite-pwa/nuxt#32]
**_How do i get rid of bad-precaching-response for manifest.webmanifest?_**
![bad precache - respons manifest-webmanifest 404](https://user-images.githubusercontent.com/125480548/231180974-715b114a-2fee-4866-94e1-4a6dc4da8902.jpg)

Here is my [repo](https://github.com/lovkyndig/kirkepostille) and [deployment](https://kirkepostille.vercel.app/)

**Comment by userquin** [comment]
@lovkyndig try adding `registerWebManifestInRouteRules: true`

**Comment by lovkyndig** [comment]
Thank you very much! Thats is something I want to try out.
