### ISSUE TITLE
PWA Module breaks Nuxt Devtools Module

### ISSUE THREAD

**Issue by RichiCoder1** [vite-pwa/nuxt#42]
I haven't gotten to the specific root of the issue, but using both the PWA module and the Devtools module results in the devtools module functionally breaking and entering a redirect loop. Disabling SW network intercept or removing the PWA module resolves the issue.

Broken:
![image](https://github.com/vite-pwa/nuxt/assets/2391878/6eb59a4e-2f42-4480-94d3-a4f82d40be63)

Working:
![image](https://github.com/vite-pwa/nuxt/assets/2391878/8908542a-b782-488f-bc0e-d50c2080cf77)

**Comment by RichiCoder1** [comment]
It looks like the service worker is doing something very bizzare to the `iframe` that the devtools loads.

**Comment by RichiCoder1** [comment]
`/__nuxt_devtools__/client/modules/overview`, though I believe it loads a different path under `/__nuxt_devtools__/client/*` initially.

**Comment by userquin** [comment]
dev plugin is using `/^\/$/`: https://github.com/vite-pwa/vite-plugin-pwa/blob/main/src/plugins/dev.ts#L135

**Comment by userquin** [comment]
are you using custom service worker (`injectManifest` strategy)?

**Comment by RichiCoder1** [comment]
Ah, this may have been a copy pasta fail on my part. Somehow `navigateFallback` got set to `/` in my config. Apologies!

**Comment by userquin** [comment]
@RichiCoder1 so, can this be closed?
