### ISSUE TITLE
How to drop some nuxt runtime config into service worker context?

### ISSUE THREAD

**Issue by cawa-93** [vite-pwa/nuxt#49]
My app needs to make requests to the api. The api endpoint is set in a runtimeConfig variable that is inlined during assembly so it can be inlined in both context. How can I drop the config into service worker context?

**Comment by userquin** [comment]
@cawa-93 have you tried to import `useRuntimeConfig` from `#app` or `#imports` and use it inside the sw (never tested)? Or maybe you can use `import.meta.env` inside the sw.

**Comment by cawa-93** [comment]
@userquin Yeap. `SyntaxError: Cannot use import statement outside a module`. Everything looks like the plugin does not process or interact with scripts at all.
![зображення](https://github.com/vite-pwa/nuxt/assets/1662812/61a20452-e41c-4d79-b07b-25c2cb5af79f)

**Comment by userquin** [comment]
@cawa-93 have you configured `devOptions.type = 'module'`?

**Comment by cawa-93** [comment]
> @cawa-93 have you configured `devOptions.type = 'module'`?

Yes. 
```
    devOptions: {
      enabled: !false,
      type: 'module',
    },
```

**Comment by userquin** [comment]
I'm getting this error:

```ts
...
import { useRuntimeConfig } from 'nuxt/app'
import { onNotificationClick, onPush } from './web-push-notifications'
import { onShareTarget } from './share-target'

declare const self: ServiceWorkerGlobalScope

self.addEventListener('message', (event) => {...})

const singleInstance = useRuntimeConfig().public.singleInstance
console.log('Single Instance', singleInstance)
```

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/d4645f5c-2698-45af-91f7-a0b35e94f1ad)

**Comment by userquin** [comment]
I suggest you to provide some `process.env` variable and use it in `define`, then access it using `import.meta.env` in the sw. Reuse the variable for nuxt runtime config entry

**Comment by userquin** [comment]
Running this script in elk.zone repo `"dev:mocked:pwa": "VITE_DEV_PWA=true nuxi dev --port 5314 --dotenv .env.mock",`:

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/9f05cd35-3c72-4477-bc37-3fb21d5f0f79)

**Comment by cawa-93** [comment]
I was confused that the default strategy was `generateSW` and my little custom script for was included as `workbox.importScripts`. It seems that I will have to change the strategy to `injectManifest` and somehow write the worker myself
