### ISSUE TITLE
How to get Runtime Caching of root "/", mixed with precache of assets.

### ISSUE THREAD

**Issue by lukeschaefer** [vite-pwa/nuxt#53]
In my Nuxt application I always SSR the home page, which has a constantly updating list of posts. I'd like to cache it at Runtime, so that if a user reloads while offline, they get the latest version they've seen. At the same time, I'd like most of the rest of my assets to be precached. I can't seem to get this to happen.

My config looks something like this:

```typescript 
export default defineNuxtConfig({
  nitro: {
   // Disabled, as I don't want to serve a prerendered page that could be days-stale:
   // prerender: {
   //   crawlLinks: false,
   //   routes: ['/'],
   // },
  },
  modules: ['@vite-pwa/nuxt'],
  pwa: {
    // Added scope/base mostly from browsing the Elk & Vitesse repos:
    scope: '/',
    base: '/',
    manifest: {   ...  },  // 
    injectRegister: 'auto',
    registerType: 'autoUpdate',
    // Disabled, since I don't want to prerender (but I might have misunderstood what this does):
    // registerWebManifestInRouteRules: true,
    workbox: {
      // Successfully precaches other assets:
      globPatterns: ['**/*.{js,css,html,png,svg,ico}'],
      // Try to Runtime Cache the home page:
      runtimeCaching: [{
        urlPattern: "/",
        handler: 'NetworkFirst',
      }]
      // Don't use navigationFallback because "/" isn't in our precache manfiest:
      // navigationFallback: '/'
    },
  },
})
```

If I uncomment the commented lines, I can get it working - however then I'm stuck with prerendering, and what I want is to have the client cache a SSR page. But when I try runtime caching, caching is flakey, because workbox gets a:

    non-precached-url: non-precached-url :: [{"url":"index.html"}]

But if it does build the Cache, it's lacking the root. Here's the difference with prerendering and not-prerendering for my Application Cache:

| With Prerender  | Trying to Runtime Cache |
| ------------- | ------------- |
| ![Screenshot 2023-06-30 4 30 53 PM](https://github.com/vite-pwa/nuxt/assets/5386710/4e814982-cf75-4700-ad46-0c4f26f87962)  | ![Screenshot 2023-06-30 4 51 13 PM](https://github.com/vite-pwa/nuxt/assets/5386710/98f71381-6b62-43ab-8943-484e4c7dd320) |
  |  17 entries (including "/") | 16 entries (missing "/") |

Is there something I'm missing?

**Comment by userquin** [comment]
You need at least 1 prerendered route to work offline using generateSW strategy.

**Comment by userquin** [comment]
You can try `navigateFallback: undefined` and let nuxt error do its work, not tested.

**Comment by lukeschaefer** [comment]
Thanks for the quick reply! I'll try that and get back

**Comment by lukeschaefer** [comment]
setting `navigateFallback: undefined` seemed to work! Thanks! I'll double check in prod

**Comment by lukeschaefer** [comment]
Works great! Thanks for the quick response, closing this 👍
