### ISSUE TITLE
Document useNuxtApp usage for TypeScript users

### ISSUE THREAD

**Issue by jf908** [vite-pwa/nuxt#60]
None of the documentation or examples demonstrate that `const { $pwa } = useNuxtApp()` must be used when lang="ts" is used otherwise $pwa will not typecheck.

Even though it's possible to use $pwa within Vue templates without useNuxtApp, it will cause a TypeScript error.

**Comment by userquin** [comment]
have you run `nuxi prepare`?

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/7cbf6539-82e6-4fda-99d6-0f134d549991)

**Comment by jf908** [comment]
> have you run `nuxi prepare`?

I think there's a misunderstanding. `const { $pwa } = useNuxtApp()` works fine but I think it should be included in the docs or in the playground. I didn't realise it existed until I read the source.

**Comment by userquin** [comment]
upps, sorry, so it is about add it to the docs:

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/488fa582-9af7-49e4-826b-a519e85572d0)

**Comment by userquin** [comment]
can you check  https://deploy-preview-70--vite-pwa-org.netlify.app/frameworks/nuxt.html in private browsing? (the sw and the storage will be removed once you close the window)

**Comment by jf908** [comment]
Thank you 👍
