### ISSUE TITLE
Service workers are not generated with static build

### ISSUE THREAD

**Issue by Applelo** [vite-pwa/nuxt#7]
Currently, when I do a `nuxt generate`, the service worker is generated (sw.js and workbox file) in .output/public but remove after that during the generation process.

## Configuration

```ts

export default defineNuxtConfig({
  modules: [
    '@vite-pwa/nuxt'
  ],
  pwa: {
    manifest: false,
    injectRegister: 'auto'
  }
})
```

**Comment by Ice-Hazymoon** [comment]
When deployed on Netlify, this issue still exists.

```js
pwa: {
    injectRegister: 'inline',
    registerType: 'autoUpdate',
    workbox: {
        navigateFallback: '/',
        globDirectory: 'dist/',
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
        offlineGoogleAnalytics: true,
    },
    client: {
        installPrompt: true,
    },
}
```

**Comment by userquin** [comment]
@Ice-Hazymoon with latest version? You should avoid configure `globDirectory`, that option should be `.nuxt/output/public`: https://github.com/vite-pwa/nuxt/blob/main/src/config.ts#L9

**Comment by Ice-Hazymoon** [comment]
Yes, it is the latest version. If I don't configure the globDirectory, a warning will appear and I still won't be able to access the sw.js.

```
2:08:44 AM: PWA v0.14.4
2:08:44 AM: mode      generateSW
2:08:44 AM: precache  1 entries (0.00 KiB)
2:08:44 AM: files generated
2:08:44 AM:   .output/public/sw.js
2:08:44 AM:   .output/public/workbox-a9fc2876.js
2:08:44 AM: [warn] warnings
2:08:44 AM:   One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/opt/build/repo/.output/public",
2:08:44 AM:   "globPattern": "**/*.{js,css,html}",
2:08:44 AM:   "globIgnores": [
2:08:44 AM: Starting post processing
2:08:44 AM:     "**/node_modules/**/*",
2:08:44 AM:     "sw.js",
2:08:44 AM:     "workbox-*.js"
2:08:45 AM: Post processing - HTML
2:08:44 AM:   ]
2:08:44 AM: }
2:08:44 AM: 
```

```
"nuxt": "^3.2.3"
"@vite-pwa/nuxt": "^0.0.6",
```

**Comment by Ice-Hazymoon** [comment]
I forked a copy of this project and then deployed it on Netlify: https://app.netlify.com/sites/earnest-halva-dda730/deploys/64038b792bd72c606bc3e1d0

![image](https://user-images.githubusercontent.com/25239977/222922532-b2d0d83a-c851-4d07-b189-5e7c57a3661e.png)

**Comment by Ice-Hazymoon** [comment]
same warning:

```
2:18:58 AM: PWA v0.14.4
2:18:58 AM: mode      generateSW
2:18:58 AM: precache  1 entries (0.00 KiB)
2:18:58 AM: files generated
2:18:58 AM:   .output/public/sw.js
2:18:58 AM:   .output/public/workbox-30e9d199.js
2:18:58 AM: [warn] warnings
2:18:58 AM:   One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/opt/build/repo/playground/.output/public",
2:18:58 AM:   "globPattern": "**/*.{js,css,html,png,svg,ico}",
2:18:58 AM:   "globIgnores": [
2:18:58 AM:     "**/node_modules/**/*",
2:18:58 AM:     "sw.js",
2:18:59 AM: Starting post processing
2:18:58 AM:     "workbox-*.js"
2:18:58 AM:   ]
2:18:58 AM: }
2:18:59 AM: Post processing - HTML
2:18:58 AM: 
```

**Comment by userquin** [comment]
@Ice-Hazymoon try configuring `globDirectory: '.nuxt/dist/client'`

**Comment by Ice-Hazymoon** [comment]
@userquin I set `workbox.globDirectory` to `.nuxt/dist/client` and `pwa.outDir` to `.nuxt/dist/client`. Then I run `nuxt generate`, but there is still no sw.js file in my dist folder. Did I miss anything?

**Comment by userquin** [comment]
@Ice-Hazymoon try configuring globDirectory: 'dist' and outDir: 'dist': https://github.com/unjs/nitro/blob/main/src/presets/netlify.ts#L49

**Comment by Ice-Hazymoon** [comment]
> globDirectory: 'dist' and outDir: 'dist'

Thank you very much, it works fine!

**Comment by userquin** [comment]
@Ice-Hazymoon great, I Will update the config.ts module, running netlify build on my local not working, I need to add a check about using nitro config.
