### ISSUE TITLE
PWA must add theme-color meta tag

### ISSUE THREAD

**Issue by modbender** [vite-pwa/nuxt#75]
So I have deployed a [site](http://nuxt-nova.netlify.app/) developed using Nuxt 3 on Netlify, and I have Lighthouse installed as plugin.

The below image is from Netlify lighthouse

![image](https://github.com/vite-pwa/nuxt/assets/25717245/d4bf8b73-13ae-4746-b787-a2a22433ce08)

Version
```
"@vite-pwa/nuxt": "^0.1.1",
```

The below is my configuration
```js
pwa: {
    registerType: "autoUpdate",
    manifest: {
      name: "Nuxt Nova",
      short_name: "NuxtNova",
      display: "standalone",
      theme_color: "#212529",
      background_color: "#212529",
      orientation: "portrait-primary",
      description: "Nuxt Nova Blog Template",
      icons: siteLogoIcons,
    },
    workbox: {
      navigateFallback: "/",
      globPatterns: ["**/*.{js,css,html,png,svg,ico}"],
    },
    client: {
      installPrompt: true,
      // you don't need to include this: only for testing purposes
      // if enabling periodic sync for update use 1 hour or so (periodicSyncForUpdates: 3600)
      periodicSyncForUpdates: 20,
    },
    // devOptions: {
    //   enabled: true,
    //   suppressWarnings: true,
    //   navigateFallbackAllowlist: [/^\/$/],
    //   type: "module",
    // },
  },
```

Since I have already added `theme_color` to the configuration, I think it would be redundant to manually add a `theme-color` meta tag separately.
This should be a part of [VitePwaManifest](https://github.com/vite-pwa/nuxt/blob/main/src/runtime/VitePwaManifest.ts)

Another suggestion is to move `VitePwaManifest` code to a plugin so that it's automatically added to all pages.

**Comment by userquin** [comment]
@modbender sorry, but this plugin will not include any metadata to the page, that's something you can do once. For web manifest icons you can use https://github.com/vite-pwa/assets-generator

**Comment by modbender** [comment]
Alright, I'll try to add the support and maybe open a PR, it's rather simple actually so.

**Comment by userquin** [comment]
@modbender there is no need, I'm working to integrate the PWA assets generator api in pwa plugin https://github.com/vite-pwa/vite-plugin-pwa/pull/621 , integrations support will also coming soon
