### ISSUE TITLE
Offline-issue of nuxt-content - not html-content

### ISSUE THREAD

**Issue by lovkyndig** [vite-pwa/nuxt#76]
`In my third (3) nuxt-content-app, who is setup in the same way as my other two apps, there is a problem with showing nuxt-content in offline modus.`

*There is a blink with opening up the app in offline modus.*
1. Picture of the first blink is exactly the same as it should be - but the problem is that it is only visibly for some milliseconds.
2. The next picture is showing the the screen that only should be visibly if the md-content is missing.

# Here is the two pictures:
## 1. Picture one showing in some milliseconds - the real nuxt-content (from content-folder)
<img width="960" alt="capture-first-picture" src="https://github.com/vite-pwa/nuxt/assets/125480548/1e3b17d2-8304-4741-a235-1e5f250070f7">

### 2. Picture two - if no nuxt-content
<img width="960" alt="capture-second-picture" src="https://github.com/vite-pwa/nuxt/assets/125480548/8793d5b5-6daa-434b-9f43-934b724c14a5">

### Link to my project
Here is the link to my [nuxt.config.ts](https://github.com/lovkyndig/nuxt3-pwa-offline/blob/main/nuxt.config.ts)

**Comment by lovkyndig** [comment]
Heree is the pwa-code:
```
pwa: {
    manifest: false, // see public/manifest.webmanifest
    strategies: 'generateSW',
    injectRegister: 'script',
    registerType: 'autoUpdate',
    useCredentials: true,
    workbox: {
      navigateFallback: '/',
      globPatterns: ['**/*.{js,css,html,png,PNG,svg}'],
      runtimeCaching: [
        {
          urlPattern: ({ url }) => { return url.pathname.startsWith('/api') },
          handler: 'CacheFirst' as const,
          options: {
            cacheName: 'api-cache',
            cacheableResponse: {
              statuses: [0, 200]
            } 
          }
        }
      ]
    },
    devOptions: {
      enabled: true,
      navigateFallback: '/',
      navigateFallbackAllowlist: [/^\/$/]
    }
  }
```

**Comment by userquin** [comment]
@lovkyndig try adding the `/api` routes to the navigate fallback deny list array (as a regex)

**Comment by lovkyndig** [comment]
Thanks @userquin for this app and trying to helpe me using it!
I added `navigateFallbackDenylist: [/\/api*/],`  in workbox between globPatterns and runtimeCaching.
I tried first with `[/^api/]` with the same negative result.

I will continue to work to try to solve this issue (on my own), but I hope I can get more suggestion about what to do:) Thanks again!

Here is the deployment on [Vercel](https://nuxt3-pwa-offline.vercel.app/)

**Comment by userquin** [comment]
It seems `/api` calls missing, open dev tools with online mode, press F5:
- filter by /api: missing
- switch to offline and press F5
- filter by /api: there are a few entries there: maybe nuxt ssr page?

api calls cannot be cached if not requested

**Comment by userquin** [comment]
maybe payload.json files? try adding `**/*/_payload.json` to globPatterns as a new entry in the array

**Comment by lovkyndig** [comment]
Thank you @userquin for helping me fix this issue.
I couldn't have fixed it without your help.

I tried out all your suggestion above, and the solution to fix it had to be done in two step.

## 1.step: How to get index (frontpage) loads properly in offline-mode?
**Add `/api`to `navigateFallbackDenylist` in `workbox`:**
```
pwa: {
  // ...
  workbox: {
    // ... keeping old code
    navigateFallbackDenylist: [/^\/api/],  // added
    runtimeCaching: [
    {
     // code for api-cache was already there
    }
    ]
  }
}

```
## 2.step: How to get api-cache to cache all other visited sites?
**Add `payloadExtraction: false` in `experimental` in `nuxt.config`:**
```
experimental: {
    payloadExtraction: false // get the api-cache loads/working
  },
  pwa: {
  // all the setup for pwa
  }
```
Thanks again so much for helping me out ot this issue!
You you can't imagine how happy I am now:)
