### ISSUE TITLE
How To? Custom service worker!

### ISSUE THREAD

**Issue by suchorski** [vite-pwa/nuxt#78]
I'm using `generateSw strategy`. Can I use `importScripts` too or do I need to use `injectManitest strategy`? I want to activate background sync and push notifications. With nuxt.config.ts I could only activate periodic sync. Thanks

**Comment by userquin** [comment]
@suchorski you can use import or importScripts in your custom service worker only with `injectManifest` strategy. You can check this entry: https://vite-pwa-org.netlify.app/guide/cookbook.html

`generateSW` strategy is about using workbox-build module via its `generateSW` function, you can only use plugins (without any code). 

`injectManifest` is about having a custom service worker, the pwa nuxt integration will build it using Vite, and then inject the precache manifest if enabled.

**Comment by suchorski** [comment]
@userquin so, when using injectManifest do I need to do all generateSW do besides my custom, right?

**Comment by userquin** [comment]
@suchorski yes, the plugin has 1 to 1 relation to workbox modules (generateSW will transpile the plugins using workbox modules for you)

**Comment by suchorski** [comment]
Thanks!
