### ISSUE TITLE
Updating Nuxt to 3.8.1 breaks the globPatterns

### ISSUE THREAD

**Issue by methodev** [vite-pwa/nuxt#93]
I have the following simple **pwa** config which works perfectly fine with Nuxt v3.8.0.

```
{
  registerType: 'autoUpdate',
  manifest: false,
  strategies: 'injectManifest',
  srcDir: 'configs',
  filename: 'sw.js',
  injectManifest: {
    globPatterns: ['**/*.{html,css,js,json,png,svg,woff2,ico,webmanifest}']
  },
  client: {
    installPrompt: true
  },
  devOptions: {
    enabled: true,
    type: 'module'
  }
}
```

However, when I update Nuxt to v3.8.1, I get this yellow warning on every build:

```
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "<MY_PROJECT_PATH>/.output/public",
  "globPattern": "**/*.{html,css,js,json,png,svg,woff2,ico,webmanifest}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "sw.js"
  ]
}
```

And, as expected, nothing is precached.

**Comment by userquin** [comment]
Can you provide a minimal repro or at least come configuration and buid process like SSR enabled, generate or build script, adapter? I'm updating the current PR to use 3.8.2 and seems to work using generate  build seems to fail in the playground here.

**Comment by userquin** [comment]
ok found the problem, public folder is not being generated it is using client, and Nitro not providing the folder:
https://github.com/vite-pwa/nuxt/blob/main/src/config.ts#L9
