### ISSUE TITLE
Include appManifest in manifestEntries

### ISSUE THREAD

**Issue by RifatMahmudno-1** [vite-pwa/nuxt#95]
Nuxt v3.8 now generates appManifest but pwa does include it. So, it breaks the behavior in offline mode.
It's enabled by default.
Read more at: [https://nuxt.com/blog/v3-8#app-manifest](https://nuxt.com/blog/v3-8#app-manifest)

**Comment by userquin** [comment]
So, the folder(s) in client assets folder for server logic...

**Comment by userquin** [comment]
@RifatMahmudno-1 reviewing the linked PR in the nuxt docs I will include the following logic when Nuxt 3.8+ detected and `experimental.appManifest` enabled:
- add `_nuxt/builds/**/*.json` to globPatterns
- remove the revision from any json file in `_nuxt/builds/` matching UUID pattern: we won't use `dontCacheBustURLsMatching`
- `/_nuxt/` is the default value for `app.buildAssetsDir`, we will use it with some extra logic to match the url workbox includes: workbox will generate those url entries using relative path: for example `{ url: '_nuxt/builds/latest.json', revision: 'xxxx' }` 

Thx, I missunderstood the issue, current version not including json files in `_nuxt/builds` folder in the sw precache manifest.

![imagen](https://github.com/vite-pwa/nuxt/assets/6311119/54180652-7458-4a95-a3f3-9d1d3bb8f6ab)

**Comment by userquin** [comment]
I'm including also logic to handle `experimental.payloadExtraction` to include `**/_payload.json` to `globPatterns`  array when enabled.

**Comment by userquin** [comment]
@RifatMahmudno-1 fixed in `v0.3.1`
